DATA    SEGMENT	
BUFFER	DB 'I love Nankai Acm.',0AH,0DH,'I love friendship.','$'
DATA    ENDS
STACK   SEGMENT  STACK PARA STACK 'STACK'			
	
STACK  ENDS
CODE   SEGMENT
	ASSUME  DS:DATA,CS:CODE,SS:STACK
START:  MOV     AX, SEG DATA
        MOV     DS, AX
	
        MOV     DX, OFFSET BUFFER
	MOV AH,9
	INT 21H
	MOV AH,4CH
	INT 21H
CODE    ENDS
        END  START

