STACK   SEGMENT  STACK
	DB      200 DUP(0)
STACK   ENDS
DATA    SEGMENT
	TAB     DB      80,85,86,71,75,96,83,56,01,02,76,84
	NO      DB      10
	ENGLISH DB      ?
DATA    ENDS

CODE    SEGMENT
ASSUME  DS:DATA,SS:STACK,CS:CODE
BEGIN:  MOV     AX,DATA
	MOV     DS,AX
	LEA     BX,TAB 
	MOV     AL,NO
	DEC     AL
	XLAT    TAB
	MOV     ENGLISH,AL
        MOV     AH,4CH
	INT     21H
CODE    ENDS
	END BEGIN
