DATA SEGMENT
  STR  DB 'Hello,World!$'
DATA ENDS			
CODE SEGMENT						
    	ASSUME CS:CODE,DS:DATA	
START: MOV AX,DATA
       MOV  DS,AX
       MOV  DX,OFFSET STR
       MOV  AH,09H			
       INT  21H
       MOV  AH,4CH			
       INT  21H
CODE ENDS						
END START		
